# Basic set up for three package managers

version: 2
updates:

  # Maintain dependencies for Maven
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
      time: "12:20"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 3

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
