name: Analyze dependencies

on:
  schedule:
    - cron: "0 22 * * *"

jobs:
  analize-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Setup java and gradle
        uses: emil-cristurean/whispers-translation-service/.github/actions/setup-java-and-gradle@main

      - name: Add build parameters
        run: printf "\nodmArtifactoryUser=${{ secrets.ODM_ARTIFACTORY_USER }}\nodmArtifactoryPassword=${{ secrets.ODM_ARTIFACTORY_PASSWORD }}\n" >> gradle.properties

      - name: Run dependencyCheckAnalyze
        run: ./gradlew --no-daemon clean dependencyCheckAnalyze

      - name: Archive dependency check reports
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: unit-tests-report
          path: build/reports/dependency-check-report.html
          retention-days: 5
