name: Analyze dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: "0 22 * * *"

jobs:
  analize-dependencies:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Setup java and gradle
        uses: emil-cristurean/whispers-translation-service/.github/actions/setup-java-and-gradle@791ee7c3bf5073fa49d921ab084dd48f88d5d043 #1.0.0

      - name: Add build parameters
        run: printf "\nodmArtifactoryUser=${{ secrets.ODM_ARTIFACTORY_USER }}\nodmArtifactoryPassword=${{ secrets.ODM_ARTIFACTORY_PASSWORD }}\n" >> gradle.properties

      - name: Run dependencyCheckAnalyze
        run: ./gradlew --no-daemon clean dependencyCheckAnalyze

      - name: Archive dependency check reports
        if: success() || failure()
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # 4.3.3
        with:
          name: unit-tests-report
          path: build/reports/dependency-check-report.html
          retention-days: 5

      - name: Upload SARIF file
        if: success() || failure()
        uses: github/codeql-action/upload-sarif@83a02f7883b12e0e4e1a146174f5e2292a01e601 # V2.16.4
        with:
          sarif_file: build/reports/dependency-check-report.sarif
