name: Build service

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # 4.1.6

      - name: Setup java and gradle
        uses: emil-cristurean/whispers-translation-service/.github/actions/setup-java-and-gradle@2f57731835683338120405e55faa0ea487359c6a #1.0.0

      - name: Add build parameters
        run: printf "\nodmArtifactoryUser=${{ secrets.ODM_ARTIFACTORY_USER }}\nodmArtifactoryPassword=${{ secrets.ODM_ARTIFACTORY_PASSWORD }}\n" >> gradle.properties

      - name: Build
        run: ./gradlew --no-daemon clean build -x test
