name: Build service

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # 4.1.1

      - name: Setup java and gradle
        uses: emil-cristurean/whispers-translation-service/.github/actions/setup-java-and-gradle@1b6ffb85738ff9def2553e2c1607a2688024b68c #1.0.0

      - name: Add build parameters
        run: printf "\nodmArtifactoryUser=${{ secrets.ODM_ARTIFACTORY_USER }}\nodmArtifactoryPassword=${{ secrets.ODM_ARTIFACTORY_PASSWORD }}\n" >> gradle.properties

      - name: Build
        run: ./gradlew --no-daemon clean build -x test
