name: Create Docker Image

on:
  workflow_dispatch:
    inputs:
      versionIncrease:
        type: choice
        description: Select a version increase
        options:
          - patch
          - minor
          - major

jobs:
  create-docker-image:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
      security-events: write

    steps:
      - name: Setup java and gradle
        uses: emil-cristurean/whispers-translation-service/.github/actions/setup-java-and-gradle@main #1.0.0

      - name: Update version
        run: ./gradlew --no-daemon clean reckonTagPush -Preckon.scope=${{ inputs.versionIncrease }} -Preckon.stage=final -x Test -DdmArtifactoryUser=${{ secrets.ODM_ARTIFACTORY_USER }} -DodmArtifactoryPassword=${{ secrets.ODM_ARTIFACTORY_PASSWORD }}

      - name: Get Latest Tag
        id: latest-tag
        run: |
          echo "LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)" >> $GITHUB_OUTPUT
          echo "LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)"

      - name: Print Latest Tag
        run: |
          echo ${{ steps.latest-tag.outputs.LATEST_TAG }}

      - name: Add build parameters
        run: printf "\nodmArtifactoryUser=${{ secrets.ODM_ARTIFACTORY_USER }}\nodmArtifactoryPassword=${{ secrets.ODM_ARTIFACTORY_PASSWORD }}\n" >> gradle.properties

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # 3.3.0

      - name: Build service docker image
        uses: docker/build-push-action@15560696de535e4014efeff63c48f16952e52dd1 # 6.2.0
        with:
          context: ./
          push: false
          tags: whsprs-translation-service:${{ steps.latest-tag.outputs.LATEST_TAG }}
          cache-from: type=gha,mode=max
          cache-to: type=gha,mode=max
          build-args: |
            ODM_ARTIFACTORY_USER=${{ secrets.ODM_ARTIFACTORY_USER }}
            ODM_ARTIFACTORY_PASSWORD=${{ secrets.ODM_ARTIFACTORY_PASSWORD }}
            GIT_LAST_COMMIT_SHA=${{ github.sha }}
