name: Dummy STAGE ROW Android workflow

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: read

jobs:
  dummy:
    name: Dummy
    uses: emil-cristurean/whispers-translation-service/.github/workflows/dummy.yml@main
    with:
      environment: 'Stage'
      market: 'ROW'
      platform: 'Android'
