name: scan with KICS and upload SARIF

on: [push]

jobs:
  kics-job:
    runs-on: ubuntu-latest
    name: kics-github-action
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Mkdir results-dir
        # make sure results dir is created
        run: mkdir -p results-dir

      - name: Run KICS Scan with SARIF result
        uses: checkmarx/kics-github-action@latest
        with:
          path: '.'
          output_path: kicsResults/
          output_formats: "json,sarif"

      - name: Show results
        run: |
          cat kicsResults/results.sarif
          cat kicsResults/results.json

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: kicsResults/results.sarif
