name: Run ktlint

on:
  push:

jobs:
  ktlint:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Setup java and gradle
        uses: emil-cristurean/whispers-translation-service/.github/actions/setup-java-and-gradle@d218be1faa0151446f59bcd4c01db1f5bd24722a #1.0.0

      - name: Add build parameters
        run: printf "\nodmArtifactoryUser=${{ secrets.ODM_ARTIFACTORY_USER }}\nodmArtifactoryPassword=${{ secrets.ODM_ARTIFACTORY_PASSWORD }}\n" >> gradle.properties

      - name: Run ktlintKotlinScriptCheck
        run: ./gradlew --no-daemon clean :ktlintKotlinScriptCheck

      - name: Read values from ktlintKotlinScriptCheck.json
        if: failure()
        run: |
          echo "FILES_COUNT=$(jq '. | length' build/reports/ktlint/ktlintKotlinScriptCheck/ktlintKotlinScriptCheck.json )" >> $GITHUB_ENV
          echo "ERRORS_COUNT=$(jq '[.[] | { "errors": .errors | length } | .errors] | add' build/reports/ktlint/ktlintKotlinScriptCheck/ktlintKotlinScriptCheck.json )" >> $GITHUB_ENV

      - name: Show ktlint script result
        if: failure()
        run: |
          {
            echo "### KTLint script"
            echo "| Number of files        | Number of errors                                  |"
            echo "| ---------------------- | ------------------------------------------------- |"
            echo "| ${{ env.FILES_COUNT }} | :exclamation:${{ env.ERRORS_COUNT }}:exclamation: |"
          } >> $GITHUB_STEP_SUMMARY

      - name: Upload ktlintKotlinScriptCheck HTML file
        if: failure()

        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # 4.3.1
        with:
          name: dependency-updates-report
          path: build/reports/ktlint/ktlintKotlinScriptCheck/ktlintKotlinScriptCheck.html
          retention-days: 5

      - name: Run ktlintMainSourceSetCheck
        run: ./gradlew --no-daemon clean :ktlintMainSourceSetCheck

      - name: Read values from ktlintMainSourceSetCheck.json
        if: failure()
        run: |
          echo "FILES_COUNT=$(jq '. | length' build/reports/ktlint/ktlintMainSourceSetCheck/ktlintMainSourceSetCheck.json )" >> $GITHUB_ENV
          echo "ERRORS_COUNT=$(jq '[.[] | { "errors": .errors | length } | .errors] | add' build/reports/ktlint/ktlintMainSourceSetCheck/ktlintMainSourceSetCheck.json )" >> $GITHUB_ENV

      - name: Show ktlint script result
        if: failure()
        run: |
          {
            echo "### KTLint script"
            echo "| Number of files        | Number of errors                                  |"
            echo "| ---------------------- | ------------------------------------------------- |"
            echo "| ${{ env.FILES_COUNT }} | :exclamation:${{ env.ERRORS_COUNT }}:exclamation: |"
          } >> $GITHUB_STEP_SUMMARY

      - name: Upload ktlintKotlinScriptCheck HTML file
        if: failure()

        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # 4.3.1
        with:
          name: dependency-updates-report
          path: build/reports/ktlint/ktlintMainSourceSetCheck/ktlintMainSourceSetCheck.html
          retention-days: 5
