name: Run unit tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup java and gradle
        uses: emil-cristurean/whispers-translation-service/.github/actions/setup-java-and-gradle@main

      - name: Add build parameters
        run: printf "\nodmArtifactoryUser=${{ secrets.ODM_ARTIFACTORY_USER }}\nodmArtifactoryPassword=${{ secrets.ODM_ARTIFACTORY_PASSWORD }}\n" >> gradle.properties

      - name: Run tests
        run: ./gradlew --no-daemon clean test --info

      - name: Archive unit tests reports
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: unit-tests-report
          path: build/reports/tests/test
          retention-days: 5

      - name: Archive jacoco reports
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: build/jacocoHtml
          retention-days: 5
