name: Run unit tests

on:
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Setup java and gradle
        uses: emil-cristurean/whispers-translation-service/.github/actions/setup-java-and-gradle@94ab5a560220c64273156341a84ee47fdf1022b1 #1.0.0

      - name: Add build parameters
        run: printf "\nodmArtifactoryUser=${{ secrets.ODM_ARTIFACTORY_USER }}\nodmArtifactoryPassword=${{ secrets.ODM_ARTIFACTORY_PASSWORD }}\n" >> gradle.properties

      - name: Run tests
        run: ./gradlew --no-daemon clean test --info

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@9379f0ccddcab154835d4e2487555ee79614fe95 # 4.2.1
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'

      - name: Archive unit tests reports
        if: success() || failure()
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # 4.3.1
        with:
          name: unit-tests-report
          path: build/reports/tests/test
          retention-days: 5

      - name: Archive jacoco reports
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # 4.3.1
        with:
          name: jacoco-report
          path: build/jacocoHtml
          retention-days: 5

      - name: JaCoCo Code Coverage Report
        id: jacoco_reporter
        uses: PavanMudigonda/jacoco-reporter@4fc6bf270fe893e8dda5467e432253a6961345b8 # 5.0
        with:
          coverage_results_path: build/reports/jacoco/test/jacocoTestReport.xml
          coverage_report_name: Coverage
          coverage_report_title: JaCoCo
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_check_run: true
          minimum_coverage: 99
          fail_below_threshold: false
          publish_only_summary: false

      - name: Show jacoco report
        if: success() || failure()
        run: |
          {
            echo "### Jacoco report"
            echo "| Outcome                 | Value                                                       |"
            echo "| ----------------------- | ----------------------------------------------------------: |"
            echo "| Code coverage %         | **${{ steps.jacoco_reporter.outputs.coveragePercentage }}** |"
            echo "| Number of Lines Covered | **${{ steps.jacoco_reporter.outputs.covered_lines }}**      |"
            echo "| Number of Lines Missed  | **${{ steps.jacoco_reporter.outputs.missed_lines }}**       |"
            echo "| Total Number of Lines   | **${{ steps.jacoco_reporter.outputs.total_lines }}**        |"
          } >> $GITHUB_STEP_SUMMARY
