name: Run unit tests

on:
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # 4.1.6

      - name: Setup java and gradle
        uses: emil-cristurean/whispers-translation-service/.github/actions/setup-java-and-gradle@c649ae018a3d591b70f966dd3e62559825ea0be3 #1.0.0

      - name: Add build parameters
        run: printf "\nodmArtifactoryUser=${{ secrets.ODM_ARTIFACTORY_USER }}\nodmArtifactoryPassword=${{ secrets.ODM_ARTIFACTORY_PASSWORD }}\n" >> gradle.properties

      - name: Run tests
        run: ./gradlew --no-daemon clean test

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@992d97d6eb2e5f3de985fbf9df6a04386874114d # 5
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'

      - name: Archive unit tests reports
        if: success() || failure()
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # 4.4.3
        with:
          name: unit-tests-report
          path: build/reports/tests/test
          retention-days: 5

      - name: Archive jacoco reports
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # 4.4.3
        with:
          name: jacoco-report
          path: build/jacocoHtml
          retention-days: 5

      - name: Powershell list folder
        shell: pwsh
        run: ls .

      - name: JaCoCo Code Coverage Report
        id: jacoco_reporter
        uses: PavanMudigonda/jacoco-reporter@4fc6bf270fe893e8dda5467e432253a6961345b8 # 5.0
        with:
          coverage_results_path: build/reports/jacoco/test/jacocoTestReport.xml
          coverage_report_name: Coverage
          coverage_report_title: JaCoCo
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_check_run: true
          minimum_coverage: 99
          fail_below_threshold: false
          publish_only_summary: false

      - name: Show jacoco report
        if: success() || failure()
        run: |
          {
            echo "### Jacoco report"
            echo "| Outcome                 | Value                                                       |"
            echo "| ----------------------- | ----------------------------------------------------------: |"
            echo "| Code coverage %         | **${{ steps.jacoco_reporter.outputs.coveragePercentage }}** |"
            echo "| Number of Lines Covered | **${{ steps.jacoco_reporter.outputs.covered_lines }}**      |"
            echo "| Number of Lines Missed  | **${{ steps.jacoco_reporter.outputs.missed_lines }}**       |"
            echo "| Total Number of Lines   | **${{ steps.jacoco_reporter.outputs.total_lines }}**        |"
          } >> $GITHUB_STEP_SUMMARY
