# Depending on the location of your Docker container
# you need to change the path to the specific Docker registry.
#
name: "Trivy docker image scan"

on:
  workflow_dispatch:

jobs:
  trivy-docker-image-scan:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # 4.1.6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # 3.3.0

      - name: Login to GHCR
        uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20 # 3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build docker image
        uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0 # 5.3.0
        with:
          context: ./
          push: true
          tags: ghcr.io/emil-cristurean/translation-service:${{ github.sha }}
          cache-from: type=gha,mode=max
          cache-to: type=gha,mode=max
          build-args: |
            ODM_ARTIFACTORY_USER=${{ secrets.ODM_ARTIFACTORY_USER }}
            ODM_ARTIFACTORY_PASSWORD=${{ secrets.ODM_ARTIFACTORY_PASSWORD }}
            GIT_LAST_COMMIT_SHA=${{ github.sha }}

      - name: Run Trivy vulnerability scanner for docker image
        uses: aquasecurity/trivy-action@b2933f565dbc598b29947660e66259e3c7bc8561 # 0.20.0
        with:
          image-ref: 'ghcr.io/emil-cristurean/translation-service:${{ github.sha }}'
          format: 'sarif'
          output: 'trivy-results.sarif'
        env:
          TRIVY_USERNAME: ${{ secrets.USERNAME }}
          TRIVY_PASSWORD: ${{ secrets.PASSWORD }}

      - name: Show results
        if: always()
        run: |
          cat trivy-results.sarif

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@83a02f7883b12e0e4e1a146174f5e2292a01e601 # V2.16.4
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Run Trivy vulnerability scanner for docker image
        uses: aquasecurity/trivy-action@b2933f565dbc598b29947660e66259e3c7bc8561 # 0.20.0
        with:
          image-ref: 'ghcr.io/emil-cristurean/translation-service:${{ github.sha }}'
          format: 'json'
          output: 'trivy-results.json'
        env:
          TRIVY_USERNAME: ${{ secrets.USERNAME }}
          TRIVY_PASSWORD: ${{ secrets.PASSWORD }}

      - name: Show results
        if: always()
        run: |
          cat trivy-results.json
